### ISSUE TITLE
unsafe default considered harmful: context message

### ISSUE THREAD

**Issue by dominictarr** [ssbc/ssb-ephemeral-keys#4]
Having a context message is a good idea, but disabling a security feature by default, while convenient, may mean that a bug disables the security feature, it's easy to disable by accident.

I suggest it's a better practice for security focused applications to error if a sensible setting isn't configured, or at least make opting into the default explicit.

This specific case might not be a really big issue, but as a matter of design principle I strongly recommend weakening security by default.

**Comment by dominictarr** [comment]
I would also recommend that the context message is a high entropy random value or hash of a long string.

**Comment by ameba23** [comment]
@dominictarr i'm happy to change it to require a context message, the only reason not to is that it's a difficult concept to explain.

> I would also recommend that the context message is a high entropy random value or hash of a long string.

we could have a minimum length for the context message.  we could also use it's hash but im not sure adding a hash would give us much since it is anyway going to be hashed into the shared secret.  i think maybe more important is that it contains something unique to the specific use, but this is harder to enforce.

**Comment by dominictarr** [comment]
@ameba23 my recommendation: use the id of the private thread that the ephemeral message will be used inside of. Yes this restricts the way that ephemeral messages can be used, but that's my point. They should be restricted to the degree that it's quite hard to use them insecurely...

If you are making something weaker because it's hard to explain, I think that's a sign to try and look at things from another angle

**Comment by ameba23** [comment]
thanks thats a good suggestion.  so that would generally be the id of the message containing the ephemeral public key, since thats what generally preceeds sending an ephemeral message.

**Comment by dominictarr** [comment]
yes that makes sense, but the way ssb-ephemeral-keys is presented, is that it's this generic thing where the key can be anything.

**Comment by ameba23** [comment]
i guess thats cos when i started it is wasn't an ssb plugin, it was just kind of a generic bunch of methods.  now that it's officially an ssb thing, we can take advantage of that to encourage it to be used in a sane way.  

so would you find it a good idea to have both the context message and database key be message id of the 'request' containing the public key?  

since we are gonna use flat files instead of a database, the 'database key' will probably be the filename.  does this pose a security risk?  to me it doesn't seem too bad since the keys themselves are stored on the filesystem anyway.  also, is using base64 strings as filenames gonna be a problem with certain operating systems?

**Comment by dominictarr** [comment]
> since we are gonna use flat files instead of a database, the 'database key' will probably be the filename. does this pose a security risk?

hmm, the context message is used by both peers, so it should be a value that is the same on both systems. So, it won't be an absolute file, it will only be a relative file. As I recommended elsewhere, if it's something that doesn't encode as a file name easily (like a base64 message id) you can just hex encode the binary value to get the file name, I think that way implementations have most flexibility.

**Comment by ameba23** [comment]
closing this as contextMessage is now obligatory
